// Generated by CIRCT firtool-1.114.1
module Adder(
  input        clock,
               reset,
  input  [7:0] io_a,
               io_b,
  output [7:0] io_sum
);

  assign io_sum = io_a + io_b;
endmodule

